include:
  - board: nice_nano_v2
    # УБЕРИТЕ shield: corne_left - он будет только в cmake-args
    cmake-args: '-DSHIELD="corne_left nice_view_adapter nice_view"'
  - board: nice_nano_v2
    cmake-args: '-DSHIELD="corne_right nice_view_adapter nice_view"'
